language: objective-c
osx_image: xcode7.3
xcode_project: ASCollectionView.xcworkspace
xcode_scheme: ASCollectionViewTests
xcode_sdk: iphonesimulator9.0

branches:
 only:
 - master

script:
- xcodebuild -workspace ASCollectionView.xcworkspace -scheme ASCollectionView -destination "platform=iOS Simulator,name=iPhone 6,OS=9.0" clean test